#!/usr/bin/env bash
# Picks the top `todo` ticket from tickets/, runs it through headless Claude
# Code + this repo's ship skill in an isolated worktree, and lands the
# result as a draft PR. Designed to be run hourly via launchd, but safe to
# run by hand for a dry run.
#
# Generated by the ticket-queue-init skill. Repo-specific knobs live in
# .claude/ticket-queue.config (sourced below) - edit that, not this script,
# for per-project tuning. If you do need to change this script's logic,
# consider whether the fix belongs upstream in the ticket-queue-init skill
# too, so other projects get it.
set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
LOG_DIR="$REPO_ROOT/automation/logs"
mkdir -p "$LOG_DIR"

if ! command -v claude >/dev/null 2>&1; then
  echo "claude CLI not found on PATH, skipping this run" >&2
  exit 0
fi

# Repo-specific config: SHIP_SKILL (name of the ship-style skill to invoke)
# and SECRET_PATHS (array of gitignored paths, relative to repo root, that
# a fresh worktree needs symlinked in to build/run - empty if none).
SHIP_SKILL="ship"
SECRET_PATHS=()
if [[ -f "$REPO_ROOT/.claude/ticket-queue.config" ]]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.claude/ticket-queue.config"
fi

# The queue must never touch whatever's checked out interactively in
# $REPO_ROOT - that can be (and often is) a dirty feature branch mid-work,
# or someone interactively committing straight to main in that same
# directory while a run is in flight (this happened during development:
# a ticket got queued via a normal `git push` to main from $REPO_ROOT
# while a run was using $REPO_ROOT as its queue worktree, and the run's
# own scope-diff check picked up that unrelated push as a false-positive
# scope violation). All queue bookkeeping and ticket work happens from a
# dedicated worktree on its own branch (queue-main-snapshot, not literally
# "main"), kept in sync with origin/main via fetch + hard reset every run.
# Using a distinct branch name - rather than literally checking out "main"
# - means this works even when $REPO_ROOT's own interactive checkout is on
# main itself; git only refuses two worktrees on the *same* branch name.
#
# Lives at .claude/worktrees/queue-main - nested inside the repo, not a
# visible sibling directory next to it. This mirrors where `claude -w`
# already places its own per-ticket worktrees, and stays out of the way
# in a normal directory listing. Needs `.claude/worktrees/` gitignored
# (ticket-queue-init's setup step adds this even in repos that otherwise
# track `.claude/`, e.g. for shared agent/skill configs).
QUEUE_MAIN="$REPO_ROOT/.claude/worktrees/queue-main"
QUEUE_BRANCH="queue-main-snapshot"
if [[ ! -d "$QUEUE_MAIN" ]]; then
  git -C "$REPO_ROOT" worktree add -B "$QUEUE_BRANCH" "$QUEUE_MAIN" main >>"$LOG_DIR/launchd.log" 2>&1
fi
cd "$QUEUE_MAIN"
git fetch origin main >>"$LOG_DIR/launchd.log" 2>&1
git checkout "$QUEUE_BRANCH" >>"$LOG_DIR/launchd.log" 2>&1
git reset --hard origin/main >>"$LOG_DIR/launchd.log" 2>&1

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

TICKET_PATH="$(python3 automation/ticket_meta.py pick-next)"
if [[ -z "$TICKET_PATH" ]]; then
  echo "no todo tickets, nothing to do"
  exit 0
fi

TICKET_ID="$(basename "$TICKET_PATH" .md)"
LOG_JSON="$LOG_DIR/${TICKET_ID}-${TIMESTAMP}.json"
LOG_TXT="$LOG_DIR/${TICKET_ID}-${TIMESTAMP}.log"

echo "picked ticket: $TICKET_PATH"

# --- 1. Lock: flip to in-progress and push the metadata-only commit ---
python3 automation/ticket_meta.py set "$TICKET_PATH" status=in-progress "locked_at=$TIMESTAMP"
git add "$TICKET_PATH"
git commit -m "Lock ticket: $TICKET_ID" >/dev/null
if ! git push origin HEAD:main 2>>"$LOG_TXT"; then
  echo "failed to push lock commit, aborting run (leaving ticket locked locally for manual inspection)" >&2
  exit 1
fi

WORKTREE_NAME="ticket-${TICKET_ID}"
TICKET_SCOPE="$(python3 automation/ticket_meta.py get "$TICKET_PATH" scope)"

# --- 2. Build the prompt for this ticket ---
PROMPT="$(sed \
  -e "s#{{TICKET_PATH}}#${TICKET_PATH}#g" \
  -e "s#{{TICKET_SCOPE}}#${TICKET_SCOPE}#g" \
  -e "s#{{SHIP_SKILL}}#${SHIP_SKILL}#g" \
  automation/ticket-prompt-template.txt)"

# --- 3. Run headless Claude Code in an isolated worktree ---
# --worktree creates a worktree (path resolved by Claude Code itself, not
# assumed here) and a matching branch named worktree-<name>, not <name>.
# It does not carry gitignored files, so anything in SECRET_PATHS needs to
# be symlinked in below once we know the resolved path.
#
# macOS has no built-in `timeout`/`gtimeout` (coreutils, not preinstalled),
# so the wall-clock cap is hand-rolled: run claude in the background, race
# it against a sleep-then-kill watchdog.
#
# No --max-budget-usd: on a subscription (not pay-as-you-go API key)
# account, a dollar cap doesn't bound anything real - there's no overage
# billing to protect against. The wall-clock timeout below is the actual
# backstop (bounds how long a stuck/looping run can tie up rate-limit
# usage). If this repo's queue ever runs on a metered API-key account
# instead, add --max-budget-usd back.
set +e
claude -w "$WORKTREE_NAME" -p "$PROMPT" \
  --output-format json \
  --permission-mode bypassPermissions \
  >"$LOG_JSON" 2>"$LOG_TXT" &
CLAUDE_PID=$!
( sleep 3600; kill -TERM "$CLAUDE_PID" 2>/dev/null ) &
WATCHDOG_PID=$!
wait "$CLAUDE_PID"
CLAUDE_EXIT=$?
kill "$WATCHDOG_PID" 2>/dev/null
wait "$WATCHDOG_PID" 2>/dev/null
set -e

# Resolve the worktree path AND branch Claude Code actually created - it
# names the branch worktree-<name>, not <name>, so don't assume the name we
# passed to -w is the branch name to push.
WORKTREE_LINE="$(git worktree list --porcelain | awk -v b="$WORKTREE_NAME" '
  /^worktree / { path=$2 }
  /^branch / { branch=$2; sub("refs/heads/", "", branch) }
  /^$/ { if (path && branch ~ b) print path"\t"branch; path=""; branch="" }
  END { if (path && branch ~ b) print path"\t"branch }
')"
WORKTREE_PATH="$(printf '%s' "$WORKTREE_LINE" | cut -f1)"
ACTUAL_BRANCH="$(printf '%s' "$WORKTREE_LINE" | cut -f2)"

if [[ -z "$WORKTREE_PATH" ]]; then
  echo "could not resolve worktree path for $WORKTREE_NAME, leaving ticket locked for manual inspection (see $LOG_TXT)" >&2
  exit 1
fi

# Symlink any declared secrets belatedly in case the session's early build
# steps needed them - most runs build early, so this mainly matters for
# reruns/manual invocation.
for secret_path in "${SECRET_PATHS[@]:-}"; do
  [[ -z "$secret_path" ]] && continue
  if [[ -f "$REPO_ROOT/$secret_path" ]]; then
    mkdir -p "$(dirname "$WORKTREE_PATH/$secret_path")"
    ln -sf "$REPO_ROOT/$secret_path" "$WORKTREE_PATH/$secret_path"
  fi
done

cleanup_worktree() {
  git worktree unlock "$WORKTREE_PATH" 2>>"$LOG_TXT" || true
  git worktree remove --force "$WORKTREE_PATH" 2>>"$LOG_TXT" || true
}
trap cleanup_worktree EXIT

if [[ $CLAUDE_EXIT -ne 0 ]]; then
  python3 automation/ticket_meta.py set "$TICKET_PATH" status=review "note=headless run failed (exit $CLAUDE_EXIT), see $LOG_TXT"
  git add "$TICKET_PATH" && git commit -m "Ticket $TICKET_ID: run failed" >/dev/null && git push origin HEAD:main
  osascript -e "display notification \"run failed, exit $CLAUDE_EXIT - see $LOG_TXT\" with title \"Ticket needs review: $TICKET_ID\"" 2>/dev/null || true
  exit 1
fi

# --- 4. Scope check ---
# Diff from the merge-base against origin/main, NOT the local "main" ref -
# this script fetches origin/main every run but never updates the local
# main branch itself (only queue-main-snapshot and the origin/main
# remote-tracking ref get refreshed). Using local "main" here caused every
# real scope-violation false-positive seen during development: it's
# whatever main last happened to be synced to by some unrelated action,
# which is stale far more often than not.
SCOPE_BASE="$(git -C "$WORKTREE_PATH" merge-base origin/main "$ACTUAL_BRANCH")"
CHANGED_FILES="$(git -C "$WORKTREE_PATH" diff --name-only "$SCOPE_BASE" "$ACTUAL_BRANCH")"
{
  echo "--- scope check debug ($(date)) ---"
  echo "TICKET_SCOPE=[$TICKET_SCOPE]"
  echo "ACTUAL_BRANCH=[$ACTUAL_BRANCH] SCOPE_BASE=[$SCOPE_BASE]"
  echo "CHANGED_FILES=[$CHANGED_FILES]"
} >>"$LOG_TXT"
OUT_OF_SCOPE=""
while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  MATCHED=0
  IFS=',' read -ra GLOBS <<< "$TICKET_SCOPE"
  for g in "${GLOBS[@]}"; do
    case "$f" in
      $g) MATCHED=1 ;;
    esac
  done
  echo "  scope-match file=[$f] matched=$MATCHED" >>"$LOG_TXT"
  if [[ $MATCHED -eq 0 ]]; then
    OUT_OF_SCOPE="${OUT_OF_SCOPE}${f}\n"
  fi
done <<< "$CHANGED_FILES"

# --- 5. Land ---
if [[ -n "$OUT_OF_SCOPE" ]]; then
  python3 automation/ticket_meta.py set "$TICKET_PATH" status=review "note=scope violation, changed files outside declared scope, see $LOG_TXT"
  git add "$TICKET_PATH" && git commit -m "Ticket $TICKET_ID: scope violation, needs manual review" >/dev/null && git push origin HEAD:main
  osascript -e "display notification \"scope violation, changed files outside declared scope\" with title \"Ticket needs review: $TICKET_ID\"" 2>/dev/null || true
  exit 0
fi

if [[ -z "$CHANGED_FILES" ]]; then
  python3 automation/ticket_meta.py set "$TICKET_PATH" status=review "note=no changes produced, see $LOG_TXT"
  git add "$TICKET_PATH" && git commit -m "Ticket $TICKET_ID: no changes produced" >/dev/null && git push origin HEAD:main
  osascript -e "display notification \"no changes produced\" with title \"Ticket needs review: $TICKET_ID\"" 2>/dev/null || true
  exit 0
fi

REPO_SLUG="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null)"
git -C "$WORKTREE_PATH" push -u origin "$ACTUAL_BRANCH"
PR_URL="$(gh pr create --draft --base main --head "$ACTUAL_BRANCH" \
  --title "Ticket: $TICKET_ID" \
  --body "Automated run for tickets/${TICKET_ID}.md. Transcript: automation/logs/${TICKET_ID}-${TIMESTAMP}.json" \
  --repo "$REPO_SLUG" 2>>"$LOG_TXT")"

python3 automation/ticket_meta.py set "$TICKET_PATH" status=review "pr=$PR_URL"
git add "$TICKET_PATH" && git commit -m "Ticket $TICKET_ID: PR opened" >/dev/null && git push origin HEAD:main

osascript -e "display notification \"$PR_URL\" with title \"Ticket ready for review: $TICKET_ID\"" 2>/dev/null || true
echo "done: $PR_URL"
